[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.devnet]
escrow = "AvdX6LEkoAmP961QwNjAUNpiuDtiQjaiSw5wR5zb9Zei"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "wallets/staging/staging-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.account]]
address = "AvdX6LEkoAmP961QwNjAUNpiuDtiQjaiSw5wR5zb9Zei"
filename = "target/deploy/escrow.json"

