# Easy Escrow - Localnet Setup Script (PowerShell)
# This script sets up a complete local Solana validator environment for testing

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Easy Escrow Localnet Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# Configuration
$KEYPAIR_DIR = ".localnet"
$MINT_DECIMALS = 6
$INITIAL_SUPPLY = 1000000000  # 1000 USDC (with 6 decimals)
$NFT_COUNT = 10

# Create keypair directory
Write-Host "`n[1/7] Creating keypair directory..." -ForegroundColor Yellow
if (!(Test-Path $KEYPAIR_DIR)) {
    New-Item -ItemType Directory -Path $KEYPAIR_DIR | Out-Null
}

# Generate test keypairs
Write-Host "`n[2/7] Generating test keypairs..." -ForegroundColor Yellow
$keypairs = @("buyer", "seller", "admin", "fee-collector", "usdc-mint-authority")

foreach ($keypair in $keypairs) {
    $keypairPath = "$KEYPAIR_DIR/$keypair.json"
    if (!(Test-Path $keypairPath)) {
        Write-Host "  - Generating $keypair keypair..." -ForegroundColor Gray
        solana-keygen new --no-bip39-passphrase --silent --outfile $keypairPath
    } else {
        Write-Host "  - $keypair keypair already exists" -ForegroundColor Gray
    }
}

# Configure Solana for localhost
Write-Host "`n[3/7] Configuring Solana CLI for localhost..." -ForegroundColor Yellow
solana config set --url localhost | Out-Null

# Check if validator is running
Write-Host "`n[4/7] Checking for running validator..." -ForegroundColor Yellow
$validatorRunning = $false
try {
    $cluster = solana cluster-version 2>&1
    if ($LASTEXITCODE -eq 0) {
        $validatorRunning = $true
        Write-Host "  ✓ Local validator is running" -ForegroundColor Green
    }
} catch {
    $validatorRunning = $false
}

if (!$validatorRunning) {
    Write-Host "  ! Local validator is not running" -ForegroundColor Red
    Write-Host "  ! Please start the validator first using: .\scripts\start-localnet-validator.ps1" -ForegroundColor Red
    Write-Host "  ! Or run: solana-test-validator --reset" -ForegroundColor Red
    exit 1
}

# Fund test accounts
Write-Host "`n[5/7] Funding test accounts with SOL..." -ForegroundColor Yellow
foreach ($keypair in $keypairs) {
    $keypairPath = "$KEYPAIR_DIR/$keypair.json"
    $address = solana address --keypair $keypairPath
    Write-Host "  - Funding $keypair ($address)..." -ForegroundColor Gray
    
    # Airdrop 10 SOL for transaction fees
    solana airdrop 10 --keypair $keypairPath | Out-Null
    
    $balance = solana balance --keypair $keypairPath
    Write-Host "    Balance: $balance" -ForegroundColor Gray
}

# Create USDC token mint
Write-Host "`n[6/7] Creating test USDC token mint..." -ForegroundColor Yellow
$mintKeypairPath = "$KEYPAIR_DIR/usdc-mint.json"
$mintAuthorityPath = "$KEYPAIR_DIR/usdc-mint-authority.json"

if (!(Test-Path $mintKeypairPath)) {
    Write-Host "  - Generating mint keypair..." -ForegroundColor Gray
    solana-keygen new --no-bip39-passphrase --silent --outfile $mintKeypairPath
}

$mintAddress = solana address --keypair $mintKeypairPath
$mintAuthority = solana address --keypair $mintAuthorityPath

Write-Host "  - Creating USDC mint..." -ForegroundColor Gray
$createMintResult = spl-token create-token --decimals $MINT_DECIMALS --mint-keypair $mintKeypairPath --mint-authority $mintAuthorityPath 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "    ✓ USDC Mint Address: $mintAddress" -ForegroundColor Green
} else {
    Write-Host "    ! Mint might already exist or creation failed" -ForegroundColor Yellow
}

# Create token accounts and distribute USDC
Write-Host "`n[7/7] Distributing USDC to test accounts..." -ForegroundColor Yellow
$testAccounts = @("buyer", "seller")

foreach ($account in $testAccounts) {
    $keypairPath = "$KEYPAIR_DIR/$account.json"
    
    Write-Host "  - Creating token account for $account..." -ForegroundColor Gray
    $tokenAccount = spl-token create-account $mintAddress --owner $keypairPath --fee-payer $keypairPath 2>&1
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "    ✓ Token account created" -ForegroundColor Green
        
        # Mint tokens to the account
        Write-Host "  - Minting 1000 USDC to $account..." -ForegroundColor Gray
        spl-token mint $mintAddress 1000 --mint-authority $mintAuthorityPath --recipient-owner $keypairPath --fee-payer $mintAuthorityPath | Out-Null
        
        $balance = spl-token balance $mintAddress --owner $keypairPath
        Write-Host "    USDC Balance: $balance" -ForegroundColor Green
    } else {
        Write-Host "    ! Token account might already exist" -ForegroundColor Yellow
    }
}

# Save environment configuration
Write-Host "`n[8/8] Saving environment configuration..." -ForegroundColor Yellow
$envConfig = @"
# Localnet Configuration - Auto-generated by setup-localnet.ps1
# DO NOT COMMIT THIS FILE - Contains test keypairs

# Solana Configuration
SOLANA_NETWORK=localnet
SOLANA_RPC_URL=http://localhost:8899
SOLANA_WS_URL=ws://localhost:8900

# Test Keypairs (paths relative to project root)
BUYER_KEYPAIR_PATH=$KEYPAIR_DIR/buyer.json
SELLER_KEYPAIR_PATH=$KEYPAIR_DIR/seller.json
ADMIN_KEYPAIR_PATH=$KEYPAIR_DIR/admin.json
FEE_COLLECTOR_KEYPAIR_PATH=$KEYPAIR_DIR/fee-collector.json

# Test Wallet Addresses
BUYER_ADDRESS=$(solana address --keypair $KEYPAIR_DIR/buyer.json)
SELLER_ADDRESS=$(solana address --keypair $KEYPAIR_DIR/seller.json)
ADMIN_ADDRESS=$(solana address --keypair $KEYPAIR_DIR/admin.json)
FEE_COLLECTOR_ADDRESS=$(solana address --keypair $KEYPAIR_DIR/fee-collector.json)

# USDC Mint Configuration
USDC_MINT_ADDRESS=$mintAddress
USDC_MINT_AUTHORITY_PATH=$KEYPAIR_DIR/usdc-mint-authority.json
USDC_MINT_DECIMALS=$MINT_DECIMALS

# Platform Configuration
PLATFORM_FEE_BPS=250
"@

$envConfig | Out-File -FilePath ".env.localnet" -Encoding UTF8

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Localnet Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "`nConfiguration saved to: .env.localnet" -ForegroundColor Yellow
Write-Host "Keypairs saved to: $KEYPAIR_DIR/" -ForegroundColor Yellow
Write-Host "`nUSCD Mint Address: $mintAddress" -ForegroundColor Cyan
Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "  1. Build and deploy your program: anchor build && anchor deploy" -ForegroundColor Gray
Write-Host "  2. Run localnet tests: npm run test:localnet" -ForegroundColor Gray
Write-Host "  3. To reset the environment: .\scripts\reset-localnet.ps1" -ForegroundColor Gray
Write-Host ""

