# Easy Escrow - Setup NFT Collection for Testing (PowerShell)
# This script creates a test NFT collection and mints sample NFTs

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Test NFT Collection" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

$KEYPAIR_DIR = ".localnet"
$NFT_COUNT = 10
$COLLECTION_NAME = "EasyEscrow Test NFTs"
$COLLECTION_SYMBOL = "EENFT"
$COLLECTION_URI = "https://arweave.net/test-collection-metadata.json"

# Check if localnet is setup
if (!(Test-Path $KEYPAIR_DIR)) {
    Write-Host "`n! Error: Localnet not setup" -ForegroundColor Red
    Write-Host "! Please run .\scripts\setup-localnet.ps1 first" -ForegroundColor Red
    exit 1
}

# Check if validator is running
Write-Host "`nChecking validator status..." -ForegroundColor Yellow
try {
    $cluster = solana cluster-version 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  ! Local validator is not running" -ForegroundColor Red
        Write-Host "  ! Please start the validator first: .\scripts\start-localnet-validator.ps1" -ForegroundColor Red
        exit 1
    }
    Write-Host "  ✓ Validator is running" -ForegroundColor Green
} catch {
    Write-Host "  ! Local validator is not running" -ForegroundColor Red
    exit 1
}

# Configure Solana for localhost
solana config set --url localhost | Out-Null

$sellerKeypair = "$KEYPAIR_DIR/seller.json"
$sellerAddress = solana address --keypair $sellerKeypair

Write-Host "`n[1/3] NFT Collection Configuration:" -ForegroundColor Yellow
Write-Host "  - Collection Name: $COLLECTION_NAME" -ForegroundColor Gray
Write-Host "  - Symbol: $COLLECTION_SYMBOL" -ForegroundColor Gray
Write-Host "  - Owner: Seller ($sellerAddress)" -ForegroundColor Gray
Write-Host "  - NFTs to mint: $NFT_COUNT" -ForegroundColor Gray

# Note: For a complete NFT implementation, you would need to:
# 1. Install Metaplex CLI or use metaplex-js library
# 2. Create a collection mint
# 3. Mint individual NFTs with metadata
# 4. Link NFTs to the collection

Write-Host "`n[2/3] Creating NFT Collection..." -ForegroundColor Yellow
Write-Host "  ! Note: This requires Metaplex Token Metadata program" -ForegroundColor Yellow
Write-Host "  ! For local testing, we'll create simple SPL tokens to simulate NFTs" -ForegroundColor Yellow

# Create NFT simulation using SPL tokens (each token represents an NFT)
$nftDir = "$KEYPAIR_DIR/nfts"
if (!(Test-Path $nftDir)) {
    New-Item -ItemType Directory -Path $nftDir | Out-Null
}

$nftAddresses = @()

Write-Host "`n[3/3] Minting test NFTs..." -ForegroundColor Yellow
for ($i = 1; $i -le $NFT_COUNT; $i++) {
    Write-Host "  - Minting NFT #$i..." -ForegroundColor Gray
    
    # Create mint for this NFT (supply = 1, decimals = 0 for NFT behavior)
    $nftMintKeypair = "$nftDir/nft-$i-mint.json"
    
    if (!(Test-Path $nftMintKeypair)) {
        solana-keygen new --no-bip39-passphrase --silent --outfile $nftMintKeypair
    }
    
    $nftMintAddress = solana address --keypair $nftMintKeypair
    
    # Create the token mint (NFT)
    $createResult = spl-token create-token --decimals 0 --mint-keypair $nftMintKeypair --mint-authority $sellerKeypair --fee-payer $sellerKeypair 2>&1
    
    if ($LASTEXITCODE -eq 0 -or $createResult -match "already") {
        # Create token account for seller
        $createAccount = spl-token create-account $nftMintAddress --owner $sellerKeypair --fee-payer $sellerKeypair 2>&1
        
        # Mint exactly 1 token (NFT)
        spl-token mint $nftMintAddress 1 --mint-authority $sellerKeypair --recipient-owner $sellerKeypair --fee-payer $sellerKeypair 2>&1 | Out-Null
        
        # Disable future minting (make it a true NFT)
        spl-token authorize $nftMintAddress mint --disable --mint-authority $sellerKeypair --fee-payer $sellerKeypair 2>&1 | Out-Null
        
        $nftAddresses += $nftMintAddress
        Write-Host "    ✓ NFT #$i: $nftMintAddress" -ForegroundColor Green
    } else {
        Write-Host "    ! Failed to create NFT #$i" -ForegroundColor Red
    }
}

# Save NFT addresses to config file
Write-Host "`nSaving NFT configuration..." -ForegroundColor Yellow
$nftConfig = @"
# Test NFT Collection Configuration
# Generated by setup-nft-collection.ps1

# Collection Info
NFT_COLLECTION_NAME=$COLLECTION_NAME
NFT_COLLECTION_SYMBOL=$COLLECTION_SYMBOL
NFT_COLLECTION_OWNER=$sellerAddress

# NFT Mint Addresses (for testing)
"@

for ($i = 0; $i -lt $nftAddresses.Count; $i++) {
    $nftConfig += "`nTEST_NFT_$($i + 1)=$($nftAddresses[$i])"
}

$nftConfig | Out-File -FilePath "$KEYPAIR_DIR/nft-collection.env" -Encoding UTF8

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "NFT Collection Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "`nCreated $($nftAddresses.Count) test NFTs" -ForegroundColor Yellow
Write-Host "Configuration saved to: $KEYPAIR_DIR/nft-collection.env" -ForegroundColor Yellow
Write-Host "`nCollection Owner: $sellerAddress" -ForegroundColor Cyan
Write-Host "`nTest NFT Addresses:" -ForegroundColor Yellow
for ($i = 0; $i -lt $nftAddresses.Count; $i++) {
    Write-Host "  NFT #$($i + 1): $($nftAddresses[$i])" -ForegroundColor Gray
}
Write-Host ""

